defmodule OvcsBus.Broker do
  @moduledoc """
  Supervised MQTT broker (Mosquitto) for the vehicle LAN.

  The relay side (`OvcsBus.Relay.Mqtt`) needs a broker to connect
  to. One firmware per vehicle — conventionally the VMS — hosts it
  by adding this module to its supervision tree; the other
  firmwares are pure clients.

  Mosquitto is spawned as a supervised OS process via `MuonTrap`,
  so a crashed broker is restarted automatically. The config file
  is generated at startup into a writable path (`/tmp` on Nerves,
  configurable via `:config_path`) with a minimal listener + allow-
  anonymous stanza. Override any of the defaults — including
  passing your own config file — via the opts map.

  ## Runtime dependency

  The firmware's rootfs must include the `mosquitto` binary (the
  standalone broker, not just the client `mosquitto_pub` /
  `mosquitto_sub`). The upstream Nerves systems don't ship it; add
  `BR2_PACKAGE_MOSQUITTO=y` to a custom Nerves system fragment and
  point `vms/firmware/mix.exs` at that fork. As a fallback during
  development you can point at a Mosquitto running on your host
  and skip `OvcsBus.Broker` entirely — only clients are needed
  then.

  ## Usage

  Add to the VMS composer:

      @impl VmsCore.Vehicle
      def bus_broker do
        %{port: 1884}   # Mosquitto listener port
      end

  `VmsCore.Application` reads `bus_broker/0` and supervises
  `OvcsBus.Broker` under the VMS root when the callback returns
  non-nil.

  ## Opts

    * `:port`          — TCP port Mosquitto listens on. Default `1884`.
    * `:config_path`   — where to write the generated config.
                         Default `/tmp/ovcs_bus_mosquitto.conf`.
    * `:config`        — literal config text; overrides the generated
                         defaults entirely when set.
    * `:executable`    — path or name of the broker binary.
                         Default `"mosquitto"` (expected on PATH).
    * `:extra_args`    — additional argv passed after `-c <config>`.
  """
  require Logger

  @default_port 1884
  @default_config_path "/tmp/ovcs_bus_mosquitto.conf"

  def child_spec(opts) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, [opts]},
      restart: :permanent,
      type: :worker
    }
  end

  def start_link(opts) do
    opts = normalize(opts)
    port = Keyword.get(opts, :port, @default_port)
    config_path = Keyword.get(opts, :config_path, @default_config_path)
    executable = Keyword.get(opts, :executable, "mosquitto")
    extra_args = Keyword.get(opts, :extra_args, [])

    :ok = write_config!(config_path, opts, port)

    Logger.info("OvcsBus.Broker starting #{executable} on :#{port} (config #{config_path})")

    MuonTrap.Daemon.start_link(executable, ["-c", config_path] ++ extra_args,
      name: __MODULE__,
      log_output: :info,
      stderr_to_stdout: true
    )
  end

  defp write_config!(path, opts, port) do
    File.mkdir_p!(Path.dirname(path))

    content =
      case Keyword.get(opts, :config) do
        nil -> default_config(port)
        text -> text
      end

    File.write!(path, content)
  end

  defp default_config(port) do
    """
    # Generated by OvcsBus.Broker — do not edit (regenerated on boot).
    listener #{port}
    allow_anonymous true
    persistence false
    log_dest stdout
    """
  end

  defp normalize(%{} = opts), do: Enum.to_list(opts)
  defp normalize(opts) when is_list(opts), do: opts
end
