defmodule RosBridge.Inference.DnnIntegrationTest do
  @moduledoc """
  Runs the DNN backend for real — load, blob, forward, decode — against
  `test/support/tiny_head.onnx`.

  That model is **ours**, generated by the snippet in
  `test/support/tiny_head.md`, not a downloaded YOLO. It is 1.5 KB, has
  zero convolution weights and a per-channel bias, so its output is
  exactly the bias broadcast over anchors: deterministic, which is what
  lets the GPU result be compared to the CPU's for equality rather than
  for plausibility. It also means these tests carry no model licence.

  Two things here cannot be tested any other way, and both were real
  bugs before these tests existed:

    * `Net.forward/1` returns a **list** of Mats, one per output layer,
      even for a single-output model.
    * Evision reports failure by *returning* `{:error, message}`, so
      `rescue` never sees it.

  What this does **not** test is detection quality — the model detects
  nothing. `dnn_test.exs` covers the decode arithmetic; this covers the
  plumbing around it.
  """
  use ExUnit.Case, async: false

  alias RosBridge.Inference.Dnn

  @model Path.expand("../../support/tiny_head.onnx", __DIR__)

  # 84 channels x 4 anchors, bias = channel/100. The 4 box attributes
  # are channels 0-3, so every anchor decodes to cx=0, cy=0.01,
  # w=0.02, h=0.03 — a degenerate box, deliberately: geometry is
  # dnn_test.exs's job.
  defp start_backend(target) do
    name = :"dnn_#{target}_#{System.unique_integer([:positive])}"

    {:ok, pid} =
      Dnn.start_link(
        name: name,
        model_path: @model,
        target: target,
        # The model's Reshape is fixed at 2x2, so the blob must be 2x2
        # too. Leaving the 640 default makes every inference fail and
        # return [] — which an assertion loop over the result would
        # then pass vacuously.
        input_size: 2,
        # Below every bias, so nothing is filtered and the plumbing is
        # what is under test.
        score_threshold: 0.0
      )

    on_exit(fn -> if Process.alive?(pid), do: GenServer.stop(pid) end)
    name
  end

  defp frame do
    Nx.broadcast(Nx.tensor(0, type: :u8), {2, 2, 3}) |> Evision.Mat.from_nx_2d()
  end

  defp detect_and_await(name) do
    assert :ok = Dnn.detect(name, 7, frame())
    assert_receive {:inference_detections, 7, detections}, 15_000

    # Non-empty is the point. Inference failing returns [], and every
    # per-detection assertion below would then hold trivially — which
    # is how the first version of this test passed while the model was
    # not running at all.
    assert detections != [], "inference produced no detections — it did not run"
    detections
  end

  describe "on the CPU" do
    test "loads the model and reports itself available" do
      name = start_backend(:cpu)
      assert Dnn.available?(name)
      refute Dnn.busy?(name)
    end

    test "a frame submitted while one is in flight is dropped, not queued" do
      # Driven through `handle_call/3` rather than the running server:
      # `tiny_head.onnx` on a 2x2 frame finishes in microseconds, so
      # there is no reliable way to catch the in-flight window from
      # outside, and a test that tried would be a coin flip.
      #
      # The clause is what matters. `RosBridge.Inference` says a frame
      # arriving mid-inference is dropped — queueing would add latency
      # to a measurement whose only value is being current — and this
      # backend answered `{:error, :busy}` never, because it used to
      # run inference inline and so was never busy.
      busy = %{net: :a_loaded_net, worker: {self(), make_ref()}}

      assert {:reply, {:error, :busy}, ^busy} =
               Dnn.handle_call({:detect, 1, frame(), self()}, nil, busy)
    end

    test "an inference that crashes drops its frame and leaves the backend up" do
      # The reason the worker is spawn_monitor and not Task.async: a
      # linked task taking the backend down would lose every later
      # frame too, and `Detections` drives the stereo depth path from
      # the same process.
      name = start_backend(:cpu)
      server = Process.whereis(name)

      assert :ok = Dnn.detect(name, 1, :not_a_mat)
      refute_receive {:inference_detections, 1, _detections}, 2_000

      assert Process.alive?(server), "a crashed inference took the backend with it"
      assert Dnn.available?(name)

      # And the next frame still works, i.e. the worker slot was
      # released rather than left occupied by a dead process.
      assert detect_and_await(name) != []
    end

    test "a frame goes in and detections come back tagged with the sequence" do
      name = start_backend(:cpu)
      detections = detect_and_await(name)

      # Every returned detection must carry the full contract from
      # `RosBridge.Inference`; a backend that omits a key fails only
      # later, inside the depth fusion.
      for d <- detections do
        assert is_integer(d.class_id) and d.class_id >= 0
        assert is_float(d.score) or is_integer(d.score)
        for key <- [:x0, :y0, :x1, :y1], do: assert(is_number(Map.fetch!(d, key)))
      end
    end
  end

  describe "on the GPU" do
    @describetag :gpu

    setup do
      if Evision.OCL.haveOpenCL() and Evision.OCL.useOpenCL() do
        :ok
      else
        # Skipped rather than failed: CI runners have no OpenCL device,
        # and a red build there would say nothing about this code.
        {:ok, skip: true}
      end
    end

    test "OpenCL produces the same numbers as the CPU", context do
      if context[:skip] do
        assert true
      else
        cpu = detect_and_await(start_backend(:cpu))
        gpu = detect_and_await(start_backend(:opencl))

        assert length(cpu) == length(gpu)

        for {c, g} <- Enum.zip(cpu, gpu) do
          assert c.class_id == g.class_id
          assert_in_delta c.score, g.score, 1.0e-5

          for key <- [:x0, :y0, :x1, :y1] do
            assert_in_delta Map.fetch!(c, key), Map.fetch!(g, key), 1.0e-4
          end
        end
      end
    end

    test "FP16 stays within half-precision tolerance of the CPU", context do
      if context[:skip] do
        assert true
      else
        cpu = detect_and_await(start_backend(:cpu))
        fp16 = detect_and_await(start_backend(:opencl_fp16))

        assert length(cpu) == length(fp16)
        # Looser than FP32 on purpose: half precision is expected to
        # differ slightly, and pretending otherwise would make this
        # test flaky on other hardware.
        for {c, f} <- Enum.zip(cpu, fp16), do: assert_in_delta(c.score, f.score, 1.0e-2)
      end
    end
  end

  describe "when the model is missing" do
    test "starts anyway and answers unavailable" do
      # The contract in `RosBridge.Inference`: losing detections is
      # acceptable, taking the stereo depth path down is not.
      name = :"dnn_absent_#{System.unique_integer([:positive])}"

      {:ok, pid} =
        Dnn.start_link(name: name, model_path: "/nonexistent/model.onnx", target: :cpu)

      on_exit(fn -> if Process.alive?(pid), do: GenServer.stop(pid) end)

      refute Dnn.available?(name)
      assert {:error, :unavailable} = Dnn.detect(name, 1, frame())
      assert Process.alive?(pid)
    end

    test "a file that is not a model is handled the same way" do
      # Evision returns `{:error, _}` here rather than raising, which a
      # `rescue` would miss entirely.
      path =
        Path.join(System.tmp_dir!(), "not_a_model_#{System.unique_integer([:positive])}.onnx")

      File.write!(path, "this is not an ONNX file")
      on_exit(fn -> File.rm(path) end)

      name = :"dnn_bad_#{System.unique_integer([:positive])}"
      {:ok, pid} = Dnn.start_link(name: name, model_path: path, target: :cpu)
      on_exit(fn -> if Process.alive?(pid), do: GenServer.stop(pid) end)

      refute Dnn.available?(name)
      assert {:error, :unavailable} = Dnn.detect(name, 1, frame())
      assert Process.alive?(pid)
    end
  end
end
