defmodule VmsCore.Vehicles.OVCS1.Composer.GenericController do
  alias VmsCore.Components.OVCS

  def generic_controllers do
    %{
      OVCS.FrontController => %{
        "controller_id" => 0,
        "digital_pin0" => "disabled",
        "digital_pin1" => "disabled",
        "digital_pin2" => "disabled",
        "digital_pin3" => "read_write",
        "digital_pin4" => "read_write",
        "digital_pin5" => "read_write",
        "digital_pin6" => "read_write",
        "digital_pin7" => "disabled",
        "digital_pin8" => "disabled",
        "digital_pin9" => "disabled",
        "digital_pin10" => "disabled",
        "digital_pin11" => "disabled",
        "digital_pin12" => "disabled",
        "digital_pin13" => "disabled",
        "digital_pin14" => "disabled",
        "digital_pin15" => "disabled",
        "digital_pin16" => "disabled",
        "digital_pin17" => "disabled",
        "digital_pin18" => "disabled",
        "pwm_pin0" => "disabled",
        "pwm_pin1" => "disabled",
        "pwm_pin2" => "disabled",
        "dac_pin0" => "disabled",
        "analog_pin0" => "disabled",
        "analog_pin1" => "disabled",
        "analog_pin2" => "disabled"
      },
      OVCS.RearController => %{
        "controller_id" => 1,
        "digital_pin0" => "disabled",
        "digital_pin1" => "disabled",
        "digital_pin2" => "disabled",
        "digital_pin3" => "read_write",
        "digital_pin4" => "read_write",
        "digital_pin5" => "read_write",
        "digital_pin6" => "read_write",
        "digital_pin7" => "read_write",
        "digital_pin8" => "disabled",
        "digital_pin9" => "disabled",
        "digital_pin10" => "disabled",
        "digital_pin11" => "disabled",
        "digital_pin12" => "disabled",
        "digital_pin13" => "disabled",
        "digital_pin14" => "disabled",
        "digital_pin15" => "disabled",
        "digital_pin16" => "disabled",
        "digital_pin17" => "disabled",
        "digital_pin18" => "disabled",
        "pwm_pin0" => "disabled",
        "pwm_pin1" => "disabled",
        "pwm_pin2" => "disabled",
        "dac_pin0" => "disabled",
        "analog_pin0" => "disabled",
        "analog_pin1" => "disabled",
        "analog_pin2" => "disabled"
      },
      OVCS.ControlsController => %{
        "controller_id" => 2,
        "digital_pin0" => "disabled",
        "digital_pin1" => "read_write",
        "digital_pin2" => "disabled",
        "digital_pin3" => "disabled",
        "digital_pin4" => "disabled",
        "digital_pin5" => "disabled",
        "digital_pin6" => "disabled",
        "digital_pin7" => "disabled",
        "digital_pin8" => "disabled",
        "digital_pin9" => "disabled",
        "digital_pin10" => "disabled",
        "digital_pin11" => "disabled",
        "digital_pin12" => "disabled",
        "digital_pin13" => "disabled",
        "digital_pin14" => "disabled",
        "digital_pin15" => "disabled",
        "digital_pin16" => "disabled",
        "digital_pin17" => "disabled",
        "digital_pin18" => "disabled",
        "pwm_pin0" => "disabled",
        "pwm_pin1" => "disabled",
        "pwm_pin2" => "disabled",
        "dac_pin0" => "disabled",
        "analog_pin0" => "enabled",
        "analog_pin1" => "enabled",
        "analog_pin2" => "disabled"
      },
      # OVCS.TestController => %{
      #   "controller_id" => 3,
      #   "digital_pin0" => "read_write",
      #   "digital_pin1" => "read_write",
      #   "digital_pin2" => "read_write",
      #   "digital_pin3" => "read_write",
      #   "digital_pin4" => "read_write",
      #   "digital_pin5" => "read_write",
      #   "digital_pin6" => "read_write",
      #   "digital_pin7" => "read_write",
      #   "digital_pin8" => "read_write",
      #   "digital_pin9" => "read_write",
      #   "digital_pin10" => "read_write",
      #   "digital_pin11" => "read_write",
      #   "digital_pin12" => "read_write",
      #   "digital_pin13" => "read_write",
      #   "digital_pin14" => "read_write",
      #   "digital_pin15" => "read_write",
      #   "digital_pin16" => "read_write",
      #   "digital_pin17" => "read_write",
      #   "digital_pin18" => "read_write",
      #   "pwm_pin0" => "enabled",
      #   "pwm_pin1" => "enabled",
      #   "pwm_pin2" => "enabled",
      #   "dac_pin0" => "enabled",
      #   "analog_pin0" => "enabled",
      #   "analog_pin1" => "enabled",
      #   "analog_pin2" => "enabled"
      # }
    }
  end
end
